image: gcr.io/k8s-staging-sig-storage/local-volume-provisioner:canary
imagePullPolicy: Always
useNodeNameOnly: true
classes:
- name: local-scsi
  hostDir: "/mnt/disks"
  fsType: ""
  storageClass: true
